#!/usr/bin/env bash
# Panama bindings, generated by jextract against the headers the DLLs were just
# built from. Everything the build knows -- which features are on, which defines
# and include paths were used -- is read back out of FFmpeg's own config rather
# than restated here, so the bindings cannot drift from the binaries.
. "$(dirname "$0")/common.sh"

: "${JEXTRACT_URL:=https://download.java.net/java/early_access/jextract/25/2/openjdk-25-jextract+2-4_linux-x64_bin.tar.gz}"
: "${BINDINGS_PACKAGE:=dev.vibeported.capture.libav.gen}"

# Headers whose public structs embed a third-party SDK type *by value*, which
# would drag that whole SDK into the bindings. AVVulkanDeviceContext holds a
# VkPhysicalDeviceFeatures2, so binding it means binding all of Vulkan -- some
# thousands of classes for an API the capture path never calls. The DLLs keep
# their Vulkan support regardless; only the Java view of it is left out.
# To bind it anyway: remove the header here and add the Vulkan include
# directory to the keep filter further down.
: "${BINDINGS_EXCLUDE_HEADERS:=libavutil/hwcontext_vulkan.h}"

FF="$SRC/ffmpeg"
CONFIG_H="$FF/config.h"
CONFIG_MAK="$FF/ffbuild/config.mak"
BINDINGS=/build/bindings
GEN="$OUT/generated-java"
WORK=/build/jextract-work

[ -f "$CONFIG_H" ] || { echo "!! $CONFIG_H missing -- run 10-ffmpeg.sh first"; exit 1; }

# --- jextract ---------------------------------------------------------------
if [ ! -x /opt/jextract/bin/jextract ]; then
  echo "== jextract: $JEXTRACT_URL"
  mkdir -p /opt/jextract
  curl -sSL --retry 3 --fail "$JEXTRACT_URL" | tar -xz -C /opt/jextract --strip-components=1
fi
/opt/jextract/bin/jextract --version

rm -rf "$WORK" "$GEN"; mkdir -p "$WORK" "$GEN"

# --- which headers does this build actually support? ------------------------
# A public header named foo.h (or hwcontext_foo.h) belongs to feature CONFIG_FOO.
# If the build turned that feature off, the header is unparseable here anyway
# because its SDK is absent -- so config.h, not trial and error, decides.
cd "$OUT/include"
headers=(); dropped=(); excluded=()
for h in $(ls lib*/*.h | grep -vE '/version(_major)?\.h$'); do
  feat=$(basename "$h" .h | sed 's/^hwcontext_//' | tr '[:lower:]' '[:upper:]')
  if [[ " $BINDINGS_EXCLUDE_HEADERS " == *" $h "* ]]; then
    excluded+=("$h")
  elif grep -q "^#define CONFIG_$feat " "$CONFIG_H" && ! grep -qx "#define CONFIG_$feat 1" "$CONFIG_H"; then
    dropped+=("$h")
  else
    headers+=("$h")
  fi
done
echo "== headers: ${#headers[@]} in, ${#dropped[@]} feature-disabled, ${#excluded[@]} excluded"
[ ${#dropped[@]}  -eq 0 ] || echo "   feature off: ${dropped[*]}"
[ ${#excluded[@]} -eq 0 ] || echo "   excluded:    ${excluded[*]}"

{
  printf '#include <%s>\n' "${headers[@]}"
  echo '#include <libav_extra.h>'
  echo '#include <cuda_min.h>'
} > "$WORK/libav_all.h"

# --- the exact defines and includes the libraries were compiled with --------
# Straight out of config.mak. HAVE_AV_CONFIG_H is excluded on purpose: it is the
# marker that says "I am FFmpeg's own source", and it makes public headers pull
# in the internal config.h. Everything else carries over verbatim.
mapfile -t ff_flags < <(
  sed -n 's/^\(CPPFLAGS\|CFLAGS\)=//p' "$CONFIG_MAK" |
  tr ' ' '\n' |
  sed "s|\$(SRC_PATH)|$FF|g" |
  grep -E '^-[DI]' |
  grep -v 'HAVE_AV_CONFIG_H' |
  sort -u
)
echo "== flags carried over from the FFmpeg build: ${ff_flags[*]}"

# jextract 25 has no -C option; clang arguments come from compile_flags.txt in
# the working directory (the clang-tooling convention). This is what makes the
# bindings LLP64 -- long is 4 bytes, as the DLLs were compiled. Parsing with the
# host's Linux target would silently produce wrong struct layouts.
{
  echo "--target=x86_64-w64-windows-gnu"
  echo "--sysroot=/usr/${TARGET}"
  printf '%s\n' "${ff_flags[@]}"
  echo "-I$BINDINGS"          # our <cuda.h> stand-in, ahead of everything
  echo "-I$OUT/include"
  echo "-I$PREFIX/include"
} > "$WORK/compile_flags.txt"

cd "$WORK"

# The cross compiler is the arbiter of whether the umbrella is sane. If this
# fails the header list is wrong, and failing here gives a real diagnostic
# instead of a puzzling jextract error.
"${CROSS_PREFIX}gcc" -fsyntax-only $(printf '%s ' "${ff_flags[@]}") \
    -I"$BINDINGS" -I"$OUT/include" -I"$PREFIX/include" libav_all.h ||
  { echo "!! the umbrella header does not compile for the target"; exit 1; }
echo "== umbrella compiles for $TARGET"

# --- generate ---------------------------------------------------------------
# The full public surface of what we built, minus the mingw CRT that comes in
# through <stdint.h> and friends. --dump-includes lists everything reachable;
# only the symbols whose own header lives in our tree are kept.
/opt/jextract/bin/jextract --dump-includes all-includes.txt libav_all.h
echo "== reachable symbols: $(grep -c . all-includes.txt)"

if grep -qE "$OUT/include|$BINDINGS/" all-includes.txt; then
  grep -E "$OUT/include|$BINDINGS/|$PREFIX/include/ffnvcodec" all-includes.txt > includes.txt
  echo "== ours: $(grep -c . includes.txt)"
  args=(@includes.txt)
else
  echo "!! --dump-includes carries no header provenance; generating unfiltered"
  args=()
fi

/opt/jextract/bin/jextract \
  -t "$BINDINGS_PACKAGE" \
  --header-class-name libav \
  --output "$GEN" \
  "${args[@]}" \
  libav_all.h

echo "== generated $(find "$GEN" -name '*.java' | wc -l) java files into ${BINDINGS_PACKAGE}"
cp all-includes.txt "$GEN/../generated-java-includes.txt" 2>/dev/null || true

# --- fix up the one thing jextract gets wrong when cross-generating ----------
# jextract takes struct layouts from the target (long is 4 bytes here, correctly
# so) but derives the *declared Java type* of C_LONG from the JVM it happens to
# be running on -- Linux, where long is 8. The result is a class that cannot
# even initialise on Windows:
#
#   ValueLayouts$OfIntImpl cannot be cast to ValueLayout$OfLong
#
# because canonicalLayouts().get("long") is JAVA_INT there. Declaring it OfInt
# is what the target actually calls for, and it is what AVIOContext.checksum and
# AVDXVA2FramesContext.surface_type need to be laid out correctly.
shared=$(find "$GEN" -name 'libav$shared.java')
[ -n "$shared" ] || { echo "!! no libav\$shared.java to normalise"; exit 1; }
if grep -q 'ValueLayout.OfLong C_LONG' "$shared"; then
  sed -i 's|ValueLayout\.OfLong C_LONG = (ValueLayout\.OfLong)|ValueLayout.OfInt C_LONG = (ValueLayout.OfInt)|' "$shared"
  echo "== normalised C_LONG to OfInt (LLP64 target)"
elif grep -q 'ValueLayout.OfInt C_LONG' "$shared"; then
  echo "== C_LONG already OfInt; jextract no longer needs the fixup"
else
  echo "!! C_LONG is declared in a shape this script does not recognise:"
  grep -n 'C_LONG ' "$shared"; exit 1
fi
