package dev.vibeported.mc.e2e.gradle

import net.neoforged.moddevgradle.dsl.NeoForgeExtension
import org.gradle.api.Action
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import javax.inject.Inject

/**
 * The whole surface of a build that runs e2e tests.
 *
 * ```kotlin
 * mcE2E {
 *     neoForge {
 *         version = "26.2.0.69"
 *         mods { create("mymod") { sourceSet(sourceSets.main.get()) } }
 *     }
 *     modId = "mymod"
 * }
 * ```
 */
abstract class McE2eExtension @Inject constructor(private val project: Project) {

    /**
     * ModDevGradle's own extension, handed over unwrapped.
     *
     * Not a facade: it is the real `NeoForgeExtension`, so anything this plugin has not thought to
     * expose is still reachable, and nothing has to be kept in step with ModDevGradle as it changes.
     */
    fun neoForge(action: Action<NeoForgeExtension>) {
        action.execute(project.extensions.getByType(NeoForgeExtension::class.java))
    }

    /** The mod under test. Its id seeds the id of the generated test mod. */
    abstract val modId: Property<String>

    /** Overrides the generated test mod id, which is otherwise [modId] plus `_e2e`. */
    abstract val e2eModId: Property<String>

    /** Name of the source set the suites live in, and so of `src/<name>/kotlin`. */
    abstract val sourceSetName: Property<String>

    /** Where the client is told to join once it is up. */
    abstract val serverAddress: Property<String>

    abstract val reportDir: DirectoryProperty

    /** How long a game process may take to reach the orchestrator before the run gives up. */
    abstract val startupTimeoutSeconds: Property<Long>

    /** How long one block invocation may take before the orchestrator stops waiting for it. */
    abstract val callTimeoutSeconds: Property<Long>

    /** How long a teleport or a turn may take to show up on the client that was asked. */
    abstract val actionTimeoutSeconds: Property<Long>

    /**
     * Client window size.
     *
     * Minecraft's own default is 854x480, which is too small to read an overlay on or to see what a
     * test is doing, so the default here is larger rather than absent.
     */
    abstract val clientWidth: Property<Int>
    abstract val clientHeight: Property<Int>

    /**
     * Whether each client moves its window so that two of them do not land in the same place.
     *
     * Off by default: a person watching a run generally wants to arrange the windows themselves.
     */
    abstract val tileWindows: Property<Boolean>

    /**
     * The Java version the game runs on. Minecraft 26.2 needs 25, and resolution fails outright on
     * anything older, so this is not a preference so much as a fact about the version.
     */
    abstract val javaVersion: Property<Int>

    /**
     * The class whose `main` the orchestrator runs once the cluster is up.
     *
     * Anything with a `main(String[])` qualifies -- a hand-written runner, or a JUnit console
     * launcher -- because by the time it is called the transport is already wired.
     */
    abstract val orchestratorMain: Property<String>

    /**
     * Clients to start before that main runs, on top of every name the compiler could resolve.
     *
     * Rarely needed: a name written as a literal is collected automatically, and a name nobody can
     * work out ahead of time starts the first time something addresses it.
     */
    abstract val clients: ListProperty<String>

    /** Extra lines for the generated `server.properties`, or replacements for the defaults. */
    abstract val serverProperties: ListProperty<String>

    /** @see BlockDslSettings */
    fun blockDsl(action: Action<BlockDslSettings>) {
        action.execute(blockDsl)
    }

    internal val blockDsl: BlockDslSettings =
        project.objects.newInstance(BlockDslSettings::class.java)
}

/**
 * A Kotlin name for every block the game loads, generated by starting it.
 *
 * ```kotlin
 * mcE2E {
 *     blockDsl {
 *         enable()
 *         namespaces = listOf("minecraft", "mymod")
 *     }
 * }
 * ```
 *
 * Off unless [enable] is called, and off is not a formality: turning it on means a build boots
 * FancyModLoader and loads every mod to read the block registry, because which blocks exist and what
 * each will accept are answers only a running game has. That is a real cost on a first sync, and it
 * is not one to impose on a build that never writes `minecraft.stone`.
 */
abstract class BlockDslSettings {

    internal abstract val enabled: Property<Boolean>

    /** Turns the generated DSL on for this build. */
    fun enable() {
        enabled.set(true)
    }

    /**
     * Which namespaces to generate for. Empty, the default, means every namespace the game loaded.
     *
     * Worth narrowing only if compiling the result starts to cost: a name that is never generated is
     * a name a suite cannot write, so the default is everything.
     */
    abstract val namespaces: ListProperty<String>
}
