package dev.vibeported.rpc

/**
 * Which role's table a procedure body belongs in.
 *
 * This exists because of dist-cleaned jars. A body touching classes that only exist on some nodes
 * cannot live in a class the other nodes have to load, and nothing in the source says which classes
 * exist where -- so the call site asserts it.
 *
 * On a file it sets the default for every call in that file; on a lambda it overrides that default
 * for one call. Bodies with no role at all go to a table every node loads, so anything they touch
 * had better be present everywhere.
 *
 * ```
 * @file:RpcRole("client")
 *
 * rpcCall(steve) { minecraft.player }             // the client table
 * rpcCall(host) @RpcRole("server") { world() }    // the server table
 * ```
 *
 * Source-retained: the compiler plugin reads it while rewriting, and nothing at runtime looks for
 * it -- by then the fact has been baked into which class the body ended up in.
 */
// Fully qualified because this package declares its own `Target`, which shadows the annotation.
@kotlin.annotation.Target(
    AnnotationTarget.EXPRESSION,
    AnnotationTarget.FILE,
    AnnotationTarget.FUNCTION,
)
@Retention(AnnotationRetention.SOURCE)
public annotation class RpcRole(public val value: String)

/**
 * Marks declarations only the compiler plugin is meant to call.
 *
 * Calling one by hand is not unsafe so much as pointless: the arguments are ids and serializers the
 * plugin computes from the source it is rewriting.
 */
@RequiresOptIn(
    message = "This declaration is generated by the RPC compiler plugin.",
    level = RequiresOptIn.Level.ERROR,
)
@Retention(AnnotationRetention.BINARY)
public annotation class PluginGenerated
