// This file is the seam between the hand-written surface and the machinery the
// plugin drives, so it is the one place that legitimately names both.
@file:OptIn(PluginGenerated::class)

package dev.vibeported.rpc

import kotlinx.serialization.KSerializer

/*
 * How a procedure is called.
 *
 * Ordinary functions, every one. Nothing here is special to the compiler plugin except the
 * `@RpcLift` parameter, which marks where a lambda is lifted -- so anybody can write another. A
 * `forEachRpcCallRandom` that shuffles its targets is a dozen lines over `rpcCallIn` and needs no
 * compiler support, because by the time it holds a body the body is just a value.
 *
 * Each call comes in two forms. The plain one fixes the receiver to [RpcScope], so a lambda written
 * at it needs no type argument. The `In` one is generic in the receiver, and is what a layer builds
 * its own vocabulary on:
 *
 * ```
 * suspend fun <R> client(name: String, @RpcLift body: RpcBody0<MinecraftClientScope, R>): R =
 *     rpcCallIn(node(name), body)
 *
 * client("alex") { minecraftClient.doClientJob() }
 * ```
 *
 * A body may not capture anything around it: it runs in another process, where those values do not
 * exist. Everything it needs arrives as an argument, which is why these come at each arity.
 *
 * Generated by tools/rpc-overloads.py. Edit that, not this.
 */

@Suppress("UNCHECKED_CAST")
private fun <R> LiftedBody.result(): KSerializer<R> = resultSerializer as KSerializer<R>

/** Runs a body on one node, against whatever receiver that node provides for [S]. */
public suspend fun <S, R> rpcCallIn(
    target: RpcTarget,
    @RpcLift body: RpcBody0<S, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, emptyList(), lifted.argSerializers, lifted.result())
}

/** @see rpcCallIn */
public suspend fun <R> rpcCall(
    target: RpcTarget,
    @RpcLift body: RpcBody0<RpcScope, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, emptyList(), lifted.argSerializers, lifted.result())
}

/** Runs a body on every matching node at once, failing as soon as any of them does. */
public suspend fun <R> forEachRpcCall(
    where: (NodeInfo) -> Boolean,
    parallel: Boolean = true,
    @RpcLift body: RpcBody0<RpcScope, R>,
): Map<NodeId, R> {
    val lifted = body.asLifted()
    return dispatchEach(
        RpcTarget.Where(where), lifted.id, lifted.role, emptyList(),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** The same, except each node reports for itself and nothing is cancelled. */
public suspend fun <R> forEachRpcCallCatching(
    where: (NodeInfo) -> Boolean,
    parallel: Boolean = true,
    @RpcLift body: RpcBody0<RpcScope, R>,
): Map<NodeId, Result<R>> {
    val lifted = body.asLifted()
    return dispatchEachCatching(
        RpcTarget.Where(where), lifted.id, lifted.role, emptyList(),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** Runs a body on one node, against whatever receiver that node provides for [S]. */
public suspend fun <S, A1, R> rpcCallIn(
    target: RpcTarget,
    a1: A1,
    @RpcLift body: RpcBody1<S, A1, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1), lifted.argSerializers, lifted.result())
}

/** @see rpcCallIn */
public suspend fun <A1, R> rpcCall(
    target: RpcTarget,
    a1: A1,
    @RpcLift body: RpcBody1<RpcScope, A1, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1), lifted.argSerializers, lifted.result())
}

/** Runs a body on every matching node at once, failing as soon as any of them does. */
public suspend fun <A1, R> forEachRpcCall(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    parallel: Boolean = true,
    @RpcLift body: RpcBody1<RpcScope, A1, R>,
): Map<NodeId, R> {
    val lifted = body.asLifted()
    return dispatchEach(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** The same, except each node reports for itself and nothing is cancelled. */
public suspend fun <A1, R> forEachRpcCallCatching(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    parallel: Boolean = true,
    @RpcLift body: RpcBody1<RpcScope, A1, R>,
): Map<NodeId, Result<R>> {
    val lifted = body.asLifted()
    return dispatchEachCatching(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** Runs a body on one node, against whatever receiver that node provides for [S]. */
public suspend fun <S, A1, A2, R> rpcCallIn(
    target: RpcTarget,
    a1: A1,
    a2: A2,
    @RpcLift body: RpcBody2<S, A1, A2, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1, a2), lifted.argSerializers, lifted.result())
}

/** @see rpcCallIn */
public suspend fun <A1, A2, R> rpcCall(
    target: RpcTarget,
    a1: A1,
    a2: A2,
    @RpcLift body: RpcBody2<RpcScope, A1, A2, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1, a2), lifted.argSerializers, lifted.result())
}

/** Runs a body on every matching node at once, failing as soon as any of them does. */
public suspend fun <A1, A2, R> forEachRpcCall(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    a2: A2,
    parallel: Boolean = true,
    @RpcLift body: RpcBody2<RpcScope, A1, A2, R>,
): Map<NodeId, R> {
    val lifted = body.asLifted()
    return dispatchEach(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1, a2),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** The same, except each node reports for itself and nothing is cancelled. */
public suspend fun <A1, A2, R> forEachRpcCallCatching(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    a2: A2,
    parallel: Boolean = true,
    @RpcLift body: RpcBody2<RpcScope, A1, A2, R>,
): Map<NodeId, Result<R>> {
    val lifted = body.asLifted()
    return dispatchEachCatching(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1, a2),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** Runs a body on one node, against whatever receiver that node provides for [S]. */
public suspend fun <S, A1, A2, A3, R> rpcCallIn(
    target: RpcTarget,
    a1: A1,
    a2: A2,
    a3: A3,
    @RpcLift body: RpcBody3<S, A1, A2, A3, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1, a2, a3), lifted.argSerializers, lifted.result())
}

/** @see rpcCallIn */
public suspend fun <A1, A2, A3, R> rpcCall(
    target: RpcTarget,
    a1: A1,
    a2: A2,
    a3: A3,
    @RpcLift body: RpcBody3<RpcScope, A1, A2, A3, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1, a2, a3), lifted.argSerializers, lifted.result())
}

/** Runs a body on every matching node at once, failing as soon as any of them does. */
public suspend fun <A1, A2, A3, R> forEachRpcCall(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    a2: A2,
    a3: A3,
    parallel: Boolean = true,
    @RpcLift body: RpcBody3<RpcScope, A1, A2, A3, R>,
): Map<NodeId, R> {
    val lifted = body.asLifted()
    return dispatchEach(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1, a2, a3),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** The same, except each node reports for itself and nothing is cancelled. */
public suspend fun <A1, A2, A3, R> forEachRpcCallCatching(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    a2: A2,
    a3: A3,
    parallel: Boolean = true,
    @RpcLift body: RpcBody3<RpcScope, A1, A2, A3, R>,
): Map<NodeId, Result<R>> {
    val lifted = body.asLifted()
    return dispatchEachCatching(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1, a2, a3),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** Runs a body on one node, against whatever receiver that node provides for [S]. */
public suspend fun <S, A1, A2, A3, A4, R> rpcCallIn(
    target: RpcTarget,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    @RpcLift body: RpcBody4<S, A1, A2, A3, A4, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1, a2, a3, a4), lifted.argSerializers, lifted.result())
}

/** @see rpcCallIn */
public suspend fun <A1, A2, A3, A4, R> rpcCall(
    target: RpcTarget,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    @RpcLift body: RpcBody4<RpcScope, A1, A2, A3, A4, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1, a2, a3, a4), lifted.argSerializers, lifted.result())
}

/** Runs a body on every matching node at once, failing as soon as any of them does. */
public suspend fun <A1, A2, A3, A4, R> forEachRpcCall(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    parallel: Boolean = true,
    @RpcLift body: RpcBody4<RpcScope, A1, A2, A3, A4, R>,
): Map<NodeId, R> {
    val lifted = body.asLifted()
    return dispatchEach(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1, a2, a3, a4),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** The same, except each node reports for itself and nothing is cancelled. */
public suspend fun <A1, A2, A3, A4, R> forEachRpcCallCatching(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    parallel: Boolean = true,
    @RpcLift body: RpcBody4<RpcScope, A1, A2, A3, A4, R>,
): Map<NodeId, Result<R>> {
    val lifted = body.asLifted()
    return dispatchEachCatching(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1, a2, a3, a4),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** Runs a body on one node, against whatever receiver that node provides for [S]. */
public suspend fun <S, A1, A2, A3, A4, A5, R> rpcCallIn(
    target: RpcTarget,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    a5: A5,
    @RpcLift body: RpcBody5<S, A1, A2, A3, A4, A5, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1, a2, a3, a4, a5), lifted.argSerializers, lifted.result())
}

/** @see rpcCallIn */
public suspend fun <A1, A2, A3, A4, A5, R> rpcCall(
    target: RpcTarget,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    a5: A5,
    @RpcLift body: RpcBody5<RpcScope, A1, A2, A3, A4, A5, R>,
): R {
    val lifted = body.asLifted()
    return dispatch(target, lifted.id, lifted.role, listOf(a1, a2, a3, a4, a5), lifted.argSerializers, lifted.result())
}

/** Runs a body on every matching node at once, failing as soon as any of them does. */
public suspend fun <A1, A2, A3, A4, A5, R> forEachRpcCall(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    a5: A5,
    parallel: Boolean = true,
    @RpcLift body: RpcBody5<RpcScope, A1, A2, A3, A4, A5, R>,
): Map<NodeId, R> {
    val lifted = body.asLifted()
    return dispatchEach(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1, a2, a3, a4, a5),
        lifted.argSerializers, lifted.result(), parallel,
    )
}

/** The same, except each node reports for itself and nothing is cancelled. */
public suspend fun <A1, A2, A3, A4, A5, R> forEachRpcCallCatching(
    where: (NodeInfo) -> Boolean,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    a5: A5,
    parallel: Boolean = true,
    @RpcLift body: RpcBody5<RpcScope, A1, A2, A3, A4, A5, R>,
): Map<NodeId, Result<R>> {
    val lifted = body.asLifted()
    return dispatchEachCatching(
        RpcTarget.Where(where), lifted.id, lifted.role, listOf(a1, a2, a3, a4, a5),
        lifted.argSerializers, lifted.result(), parallel,
    )
}
