package dev.vibeported.rpc

/*
 * The shape of a procedure body, at each arity.
 *
 * A `fun interface` rather than a function type, and that is what makes the whole design work: a
 * lambda still converts to one, receiver and all, so a body reads exactly as it would have -- while
 * the value that actually travels is an ordinary object the compiler plugin can construct.
 *
 * `S` is the receiver the body runs against, so a layer can offer its own: a body written for a game
 * client sees that client's scope, and one written for a worker sees the worker's.
 *
 * Generated by tools/rpc-overloads.py. Edit that, not this.
 */

/** A body taking no arguments. */
public fun interface RpcBody0<S, R> {
    public suspend fun S.run(): R
}

/** A body taking 1 argument. */
public fun interface RpcBody1<S, A1, R> {
    public suspend fun S.run(a1: A1): R
}

/** A body taking 2 arguments. */
public fun interface RpcBody2<S, A1, A2, R> {
    public suspend fun S.run(a1: A1, a2: A2): R
}

/** A body taking 3 arguments. */
public fun interface RpcBody3<S, A1, A2, A3, R> {
    public suspend fun S.run(a1: A1, a2: A2, a3: A3): R
}

/** A body taking 4 arguments. */
public fun interface RpcBody4<S, A1, A2, A3, A4, R> {
    public suspend fun S.run(a1: A1, a2: A2, a3: A3, a4: A4): R
}

/** A body taking 5 arguments. */
public fun interface RpcBody5<S, A1, A2, A3, A4, A5, R> {
    public suspend fun S.run(a1: A1, a2: A2, a3: A3, a4: A4, a5: A5): R
}
