package dev.vibeported.mc.e2e

/**
 * The generated per-file dispatch table.
 *
 * The compiler plugin emits one `object <FileFacade>$E2eBlocks : E2eBlockTable` per source file that
 * declares tests, holding every lifted block body as a private suspend method. Because lookup is by
 * a stable string id, a node can run a block whose source lived in another process entirely.
 */
public interface E2eBlockTable {
    /**
     * Runs one block, or throws [NoSuchBlockException] if this table does not own it.
     *
     * There is deliberately no listing of the ids a table holds: the generated index already records
     * every block against its table, and a second, generated copy of the same fact could drift.
     */
    public suspend fun invoke(id: String, scope: BlockScope): Any?
}

/**
 * Marks declarations that only the compiler plugin is meant to call.
 *
 * Calling one by hand is not unsafe so much as pointless: the arguments are ids the plugin computes.
 */
@RequiresOptIn(
    message = "This overload is generated by the minecraft-e2e compiler plugin.",
    level = RequiresOptIn.Level.ERROR,
)
@Retention(AnnotationRetention.BINARY)
public annotation class E2eGenerated
