#!/usr/bin/env python3
"""Generates the server/client call overloads.

Ten arguments each, for two roles, is forty-odd near-identical declarations. They are boilerplate in
the strict sense -- every one says the same thing about a different arity -- so they are generated
rather than typed, and a change to the shape is a change to this file instead of forty edits.

    python tools/call-overloads.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(
    HERE, "..", "e2e-core", "src", "main", "kotlin", "dev", "vibeported", "mc", "e2e", "Calls.kt"
)

MAX_ARGS = 10

HEADER = '''package dev.vibeported.mc.e2e

/*
 * Generated by tools/call-overloads.py. Edit that, not this.
 *
 * Every one of these throws. The compiler plugin rewrites each call site into `invokeBlock` with the
 * ids and types it worked out, so a body that reaches this has been compiled without the plugin --
 * and saying so plainly beats failing later with something that looks like a transport problem.
 */

/**
 * Runs [body] on the dedicated server and returns what it produced.
 *
 * Called from the server itself the body runs in place, with these very objects. Called from
 * anywhere else the arguments are encoded, the block runs over there, and the result comes back --
 * so a failure inside it surfaces as an exception at this line, and `try`/`catch` works across the
 * boundary like it does anywhere else.
 *
 * [body] may not capture anything from around it: it runs in another process, where the things it
 * would have captured do not exist. Pass them as arguments instead, which is checked at compile
 * time.
 */
public suspend fun <R> server(body: suspend ServerScope.() -> R): R = notApplied("server")

/**
 * Runs [body] on the client called [name] and returns what it produced.
 *
 * The name is the client's username, and the client it addresses is started before the run if the
 * name could be worked out at compile time, or on demand the first time it is used if it could not.
 *
 * @see server for the capture and argument rules, which are identical.
 */
public suspend fun <R> client(name: String, body: suspend ClientScope.() -> R): R = notApplied("client")
'''

FOOTER = '''
private fun notApplied(what: String): Nothing = throw E2ePluginNotAppliedException("$what { }")
'''


def overload(role, scope, arity):
    types = ", ".join("A%d" % i for i in range(1, arity + 1))
    params = ", ".join("a%d: A%d" % (i, i) for i in range(1, arity + 1))
    lambda_args = ", ".join("A%d" % i for i in range(1, arity + 1))
    leading = "name: String, " if role == "client" else ""
    return (
        "public suspend fun <%s, R> %s(\n    %s%s,\n    body: suspend %s.(%s) -> R,\n): R = notApplied(\"%s\")\n"
        % (types, role, leading, params, scope, lambda_args, role)
    )


def main():
    parts = [HEADER]
    for role, scope in (("server", "ServerScope"), ("client", "ClientScope")):
        parts.append("\n// -- %s, by arity %s\n\n" % (role, "-" * (60 - len(role))))
        for arity in range(1, MAX_ARGS + 1):
            parts.append(overload(role, scope, arity))
            parts.append("\n")
    parts.append(FOOTER)

    with open(os.path.abspath(OUT), "w", encoding="utf-8", newline="\n") as out:
        out.write("".join(parts))
    print("wrote %s (%d overloads)" % (os.path.relpath(OUT, os.path.join(HERE, "..")), MAX_ARGS * 2 + 2))


if __name__ == "__main__":
    main()
