#!/usr/bin/env python3
"""
Writes `server { }` and `client { }` at every arity.

A body may not capture anything around it -- it runs in another process -- so everything it needs
arrives as an argument, and both calls therefore exist once per arity. That is a lot of
near-identical Kotlin, which is where a typo hides.

    py -3 tools/mcdriver-calls.py [--check]

Nothing here is special to the compiler plugin. `server` and `client` are ordinary functions that
take a body at an `@RpcLift` parameter and hand it to `rpcCallIn`; the role on that parameter is
what puts their bodies in different tables, which is what a dist-cleaned server depends on.
"""

import argparse
import difflib
import pathlib
import sys

MAX_ARITY = 5
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "mc-driver/driver/src/main/kotlin/dev/vibeported/mc/driver/Calls.kt"

HEADER = '''package dev.vibeported.mc.driver

import dev.vibeported.rpc.RpcBody0
import dev.vibeported.rpc.RpcBody1
import dev.vibeported.rpc.RpcBody2
import dev.vibeported.rpc.RpcBody3
import dev.vibeported.rpc.RpcBody4
import dev.vibeported.rpc.RpcBody5
import dev.vibeported.rpc.RpcLift
import dev.vibeported.rpc.node
import dev.vibeported.rpc.rpcCallIn

/*
 * How anything reaches the two sides of the game.
 *
 * These two are the only things in this driver that push a receiver. Every other method here is a
 * free function that happens to be written in terms of one of them, so a caller composes plain
 * calls and reaches for a block only when a sequence should cross the wire once instead of five
 * times.
 *
 * Ordinary functions, at that. They take a body at an `@RpcLift` parameter and hand it to
 * `rpcCallIn`, and the compiler plugin has never heard of either of them -- which is the whole
 * point of marking the parameter rather than the function: anybody can write another one.
 *
 * The role on that parameter is what decides which generated table a body lands in. `client`
 * bodies go somewhere a dedicated server never looks, because that server's classpath cannot load
 * the classes they touch.
 *
 * Generated by tools/mcdriver-calls.py. Edit that, not this.
 */
'''


def args_of(n):
    return [f"a{i}" for i in range(1, n + 1)]


def calls():
    out = [HEADER]
    for n in range(MAX_ARITY + 1):
        names = args_of(n)
        types = [name.upper() for name in names]
        tv = "".join(t + ", " for t in types)
        declared = "".join(f"    {name}: {name.upper()},\n" for name in names)
        passed = "".join(name + ", " for name in names)

        out.append(
            "/**\n"
            " * Runs [body] on the dedicated server and returns what it produced.\n"
            " *\n"
            " * Called from the server itself the body runs in place, with these very objects.\n"
            " * Called from anywhere else the arguments are encoded, the body runs over there, and\n"
            " * the result comes back -- so a failure inside it surfaces as an exception at this\n"
            " * line, and `try`/`catch` works across the boundary as it does anywhere else.\n"
            " *\n"
            " * [body] may not capture anything from around it: it runs in another process, where\n"
            " * the things it would have captured do not exist. Pass them as arguments instead,\n"
            " * which is checked at compile time.\n"
            " */\n"
            f"public suspend fun <{tv}R> server(\n"
            f"{declared}"
            f'    @RpcLift("server") body: RpcBody{n}<ServerScope, {tv}R>,\n'
            f"): R = rpcCallIn(node(SERVER_NODE), {passed}body)\n"
        )
        out.append(
            "/**\n"
            " * Runs [body] on the client called [name] and returns what it produced.\n"
            " *\n"
            " * The name is the node's name, which for a game client is also its username.\n"
            " * Whether that client is running is not this driver's business: starting a process is\n"
            " * a job for whatever launched the cluster.\n"
            " *\n"
            " * @see server for the capture and argument rules, which are identical.\n"
            " */\n"
            f"public suspend fun <{tv}R> client(\n"
            "    name: String,\n"
            f"{declared}"
            f'    @RpcLift("client") body: RpcBody{n}<ClientScope, {tv}R>,\n'
            f"): R = rpcCallIn(node(name), {passed}body)\n"
        )
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()

    content = calls()
    if options.check:
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n")
        if current != content:
            sys.stdout.writelines(
                difflib.unified_diff(
                    current.splitlines(True), content.splitlines(True),
                    "Calls.kt (on disk)", "Calls.kt (generated)",
                )
            )
            print("\nEdit tools/mcdriver-calls.py and regenerate.", file=sys.stderr)
            return 1
        print("Calls.kt matches the generator")
        return 0

    OUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
