#!/usr/bin/env python3
"""
Writes the two files that only differ by arity: RpcBody.kt and Calls.kt.

A body may not capture anything around it -- it runs in another process, where those values do not
exist -- so everything it needs has to arrive as an argument, and every call therefore comes at
each arity. That is a lot of near-identical Kotlin, and near-identical Kotlin maintained by hand is
where a typo hides. Raising the ceiling is a one-line change here.

    py -3 tools/rpc-overloads.py [--check]

--check regenerates into memory and diffs, which is what a build or a review wants: it fails if
either file was edited by hand instead of here.
"""

import argparse
import difflib
import pathlib
import sys

MAX_ARITY = 5
ROOT = pathlib.Path(__file__).resolve().parent.parent
CORE = ROOT / "rpc/core/src/main/kotlin/dev/vibeported/rpc"

BODIES_HEADER = '''package dev.vibeported.rpc

/*
 * The shape of a procedure body, at each arity.
 *
 * A `fun interface` rather than a function type, and that is what makes the whole design work: a
 * lambda still converts to one, receiver and all, so a body reads exactly as it would have -- while
 * the value that actually travels is an ordinary object the compiler plugin can construct.
 *
 * `S` is the receiver the body runs against, so a layer can offer its own: a body written for a game
 * client sees that client's scope, and one written for a worker sees the worker's.
 *
 * Generated by tools/rpc-overloads.py. Edit that, not this.
 */
'''

CALLS_HEADER = '''// This file is the seam between the hand-written surface and the machinery the
// plugin drives, so it is the one place that legitimately names both.
@file:OptIn(PluginGenerated::class)

package dev.vibeported.rpc

import kotlinx.serialization.KSerializer

/*
 * How a procedure is called.
 *
 * Ordinary functions, every one. Nothing here is special to the compiler plugin except the
 * `@RpcLift` parameter, which marks where a lambda is lifted -- so anybody can write another. A
 * `forEachRpcCallRandom` that shuffles its targets is a dozen lines over `rpcCallIn` and needs no
 * compiler support, because by the time it holds a body the body is just a value.
 *
 * Each call comes in two forms. The plain one fixes the receiver to [RpcScope], so a lambda written
 * at it needs no type argument. The `In` one is generic in the receiver, and is what a layer builds
 * its own vocabulary on:
 *
 * ```
 * suspend fun <R> client(name: String, @RpcLift body: RpcBody0<MinecraftClientScope, R>): R =
 *     rpcCallIn(node(name), body)
 *
 * client("alex") { minecraftClient.doClientJob() }
 * ```
 *
 * A body may not capture anything around it: it runs in another process, where those values do not
 * exist. Everything it needs arrives as an argument, which is why these come at each arity.
 *
 * Generated by tools/rpc-overloads.py. Edit that, not this.
 */

@Suppress("UNCHECKED_CAST")
private fun <R> LiftedBody.result(): KSerializer<R> = resultSerializer as KSerializer<R>
'''


def args_of(n):
    return [f"a{i}" for i in range(1, n + 1)]


def bodies():
    out = [BODIES_HEADER]
    for n in range(MAX_ARITY + 1):
        names = args_of(n)
        types = [name.upper() for name in names]
        params = ", ".join(f"{name}: {name.upper()}" for name in names)
        generics = ", ".join(["S"] + types + ["R"])
        plural = "no arguments" if n == 0 else f"{n} argument" + ("s" if n > 1 else "")
        out.append(
            f"/** A body taking {plural}. */\n"
            f"public fun interface RpcBody{n}<{generics}> {{\n"
            f"    public suspend fun S.run({params}): R\n"
            f"}}\n"
        )
    return "\n".join(out)


def calls():
    out = [CALLS_HEADER]
    for n in range(MAX_ARITY + 1):
        names = args_of(n)
        types = [name.upper() for name in names]
        # Each argument on its own line, so a five-argument call still reads down the page.
        declared = "".join(f"    {name}: {name.upper()},\n" for name in names)
        passed = "emptyList()" if n == 0 else "listOf(" + ", ".join(names) + ")"
        body_type = f"RpcBody{n}<%s{''.join(t + ', ' for t in types)}R>"
        tv = "".join(t + ", " for t in types)

        out.append(
            "/** Runs a body on one node, against whatever receiver that node provides for [S]. */\n"
            f"public suspend fun <S, {tv}R> rpcCallIn(\n"
            "    target: RpcTarget,\n"
            f"{declared}"
            f"    @RpcLift body: {body_type % 'S, '},\n"
            "): R {\n"
            "    val lifted = body.asLifted()\n"
            f"    return dispatch(target, lifted.id, lifted.role, {passed}, "
            "lifted.argSerializers, lifted.result())\n"
            "}\n"
        )
        out.append(
            "/** @see rpcCallIn */\n"
            f"public suspend fun <{tv}R> rpcCall(\n"
            "    target: RpcTarget,\n"
            f"{declared}"
            f"    @RpcLift body: {body_type % 'RpcScope, '},\n"
            "): R {\n"
            "    val lifted = body.asLifted()\n"
            f"    return dispatch(target, lifted.id, lifted.role, {passed}, "
            "lifted.argSerializers, lifted.result())\n"
            "}\n"
        )
        for name, doc, dispatcher, result in (
            (
                "forEachRpcCall",
                "Runs a body on every matching node at once, failing as soon as any of them does.",
                "dispatchEach",
                "Map<NodeId, R>",
            ),
            (
                "forEachRpcCallCatching",
                "The same, except each node reports for itself and nothing is cancelled.",
                "dispatchEachCatching",
                "Map<NodeId, Result<R>>",
            ),
        ):
            out.append(
                f"/** {doc} */\n"
                f"public suspend fun <{tv}R> {name}(\n"
                "    where: (NodeInfo) -> Boolean,\n"
                f"{declared}"
                "    parallel: Boolean = true,\n"
                f"    @RpcLift body: {body_type % 'RpcScope, '},\n"
                f"): {result} {{\n"
                "    val lifted = body.asLifted()\n"
                f"    return {dispatcher}(\n"
                f"        RpcTarget.Where(where), lifted.id, lifted.role, {passed},\n"
                "        lifted.argSerializers, lifted.result(), parallel,\n"
                "    )\n"
                "}\n"
            )
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()

    written = {CORE / "RpcBody.kt": bodies(), CORE / "Calls.kt": calls()}
    stale = False
    for path, content in written.items():
        if options.check:
            current = path.read_text(encoding="utf-8").replace("\r\n", "\n")
            if current != content:
                stale = True
                sys.stdout.writelines(
                    difflib.unified_diff(
                        current.splitlines(True),
                        content.splitlines(True),
                        f"{path.name} (on disk)",
                        f"{path.name} (generated)",
                    )
                )
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        print("\nEdit tools/rpc-overloads.py and regenerate.", file=sys.stderr)
        return 1
    if options.check:
        print("both files match the generator")
    return 0


if __name__ == "__main__":
    sys.exit(main())
