package dev.vibeported.mc.driver

import dev.vibeported.rpc.RpcBody0
import dev.vibeported.rpc.RpcBody1
import dev.vibeported.rpc.RpcBody2
import dev.vibeported.rpc.RpcBody3
import dev.vibeported.rpc.RpcBody4
import dev.vibeported.rpc.RpcBody5
import dev.vibeported.rpc.RpcLift
import dev.vibeported.rpc.node
import dev.vibeported.rpc.rpcCallIn

/*
 * How anything reaches the two sides of the game.
 *
 * These two are the only things in this driver that push a receiver. Every other method here is a
 * free function that happens to be written in terms of one of them, so a caller composes plain
 * calls and reaches for a block only when a sequence should cross the wire once instead of five
 * times.
 *
 * Ordinary functions, at that. They take a body at an `@RpcLift` parameter and hand it to
 * `rpcCallIn`, and the compiler plugin has never heard of either of them -- which is the whole
 * point of marking the parameter rather than the function: anybody can write another one.
 *
 * The role on that parameter is what decides which generated table a body lands in. `client`
 * bodies go somewhere a dedicated server never looks, because that server's classpath cannot load
 * the classes they touch.
 *
 * Generated by tools/mcdriver-calls.py. Edit that, not this.
 */

/**
 * Runs [body] on the dedicated server and returns what it produced.
 *
 * Called from the server itself the body runs in place, with these very objects.
 * Called from anywhere else the arguments are encoded, the body runs over there, and
 * the result comes back -- so a failure inside it surfaces as an exception at this
 * line, and `try`/`catch` works across the boundary as it does anywhere else.
 *
 * [body] may not capture anything from around it: it runs in another process, where
 * the things it would have captured do not exist. Pass them as arguments instead,
 * which is checked at compile time.
 */
public suspend fun <R> server(
    @RpcLift("server") body: RpcBody0<ServerScope, R>,
): R = rpcCallIn(node(SERVER_NODE), body)

/**
 * Runs [body] on the client called [name] and returns what it produced.
 *
 * The name is the node's name, which for a game client is also its username.
 * Whether that client is running is not this driver's business: starting a process is
 * a job for whatever launched the cluster.
 *
 * @see server for the capture and argument rules, which are identical.
 */
public suspend fun <R> client(
    name: String,
    @RpcLift("client") body: RpcBody0<ClientScope, R>,
): R = rpcCallIn(node(name), body)

/**
 * Runs [body] on the dedicated server and returns what it produced.
 *
 * Called from the server itself the body runs in place, with these very objects.
 * Called from anywhere else the arguments are encoded, the body runs over there, and
 * the result comes back -- so a failure inside it surfaces as an exception at this
 * line, and `try`/`catch` works across the boundary as it does anywhere else.
 *
 * [body] may not capture anything from around it: it runs in another process, where
 * the things it would have captured do not exist. Pass them as arguments instead,
 * which is checked at compile time.
 */
public suspend fun <A1, R> server(
    a1: A1,
    @RpcLift("server") body: RpcBody1<ServerScope, A1, R>,
): R = rpcCallIn(node(SERVER_NODE), a1, body)

/**
 * Runs [body] on the client called [name] and returns what it produced.
 *
 * The name is the node's name, which for a game client is also its username.
 * Whether that client is running is not this driver's business: starting a process is
 * a job for whatever launched the cluster.
 *
 * @see server for the capture and argument rules, which are identical.
 */
public suspend fun <A1, R> client(
    name: String,
    a1: A1,
    @RpcLift("client") body: RpcBody1<ClientScope, A1, R>,
): R = rpcCallIn(node(name), a1, body)

/**
 * Runs [body] on the dedicated server and returns what it produced.
 *
 * Called from the server itself the body runs in place, with these very objects.
 * Called from anywhere else the arguments are encoded, the body runs over there, and
 * the result comes back -- so a failure inside it surfaces as an exception at this
 * line, and `try`/`catch` works across the boundary as it does anywhere else.
 *
 * [body] may not capture anything from around it: it runs in another process, where
 * the things it would have captured do not exist. Pass them as arguments instead,
 * which is checked at compile time.
 */
public suspend fun <A1, A2, R> server(
    a1: A1,
    a2: A2,
    @RpcLift("server") body: RpcBody2<ServerScope, A1, A2, R>,
): R = rpcCallIn(node(SERVER_NODE), a1, a2, body)

/**
 * Runs [body] on the client called [name] and returns what it produced.
 *
 * The name is the node's name, which for a game client is also its username.
 * Whether that client is running is not this driver's business: starting a process is
 * a job for whatever launched the cluster.
 *
 * @see server for the capture and argument rules, which are identical.
 */
public suspend fun <A1, A2, R> client(
    name: String,
    a1: A1,
    a2: A2,
    @RpcLift("client") body: RpcBody2<ClientScope, A1, A2, R>,
): R = rpcCallIn(node(name), a1, a2, body)

/**
 * Runs [body] on the dedicated server and returns what it produced.
 *
 * Called from the server itself the body runs in place, with these very objects.
 * Called from anywhere else the arguments are encoded, the body runs over there, and
 * the result comes back -- so a failure inside it surfaces as an exception at this
 * line, and `try`/`catch` works across the boundary as it does anywhere else.
 *
 * [body] may not capture anything from around it: it runs in another process, where
 * the things it would have captured do not exist. Pass them as arguments instead,
 * which is checked at compile time.
 */
public suspend fun <A1, A2, A3, R> server(
    a1: A1,
    a2: A2,
    a3: A3,
    @RpcLift("server") body: RpcBody3<ServerScope, A1, A2, A3, R>,
): R = rpcCallIn(node(SERVER_NODE), a1, a2, a3, body)

/**
 * Runs [body] on the client called [name] and returns what it produced.
 *
 * The name is the node's name, which for a game client is also its username.
 * Whether that client is running is not this driver's business: starting a process is
 * a job for whatever launched the cluster.
 *
 * @see server for the capture and argument rules, which are identical.
 */
public suspend fun <A1, A2, A3, R> client(
    name: String,
    a1: A1,
    a2: A2,
    a3: A3,
    @RpcLift("client") body: RpcBody3<ClientScope, A1, A2, A3, R>,
): R = rpcCallIn(node(name), a1, a2, a3, body)

/**
 * Runs [body] on the dedicated server and returns what it produced.
 *
 * Called from the server itself the body runs in place, with these very objects.
 * Called from anywhere else the arguments are encoded, the body runs over there, and
 * the result comes back -- so a failure inside it surfaces as an exception at this
 * line, and `try`/`catch` works across the boundary as it does anywhere else.
 *
 * [body] may not capture anything from around it: it runs in another process, where
 * the things it would have captured do not exist. Pass them as arguments instead,
 * which is checked at compile time.
 */
public suspend fun <A1, A2, A3, A4, R> server(
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    @RpcLift("server") body: RpcBody4<ServerScope, A1, A2, A3, A4, R>,
): R = rpcCallIn(node(SERVER_NODE), a1, a2, a3, a4, body)

/**
 * Runs [body] on the client called [name] and returns what it produced.
 *
 * The name is the node's name, which for a game client is also its username.
 * Whether that client is running is not this driver's business: starting a process is
 * a job for whatever launched the cluster.
 *
 * @see server for the capture and argument rules, which are identical.
 */
public suspend fun <A1, A2, A3, A4, R> client(
    name: String,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    @RpcLift("client") body: RpcBody4<ClientScope, A1, A2, A3, A4, R>,
): R = rpcCallIn(node(name), a1, a2, a3, a4, body)

/**
 * Runs [body] on the dedicated server and returns what it produced.
 *
 * Called from the server itself the body runs in place, with these very objects.
 * Called from anywhere else the arguments are encoded, the body runs over there, and
 * the result comes back -- so a failure inside it surfaces as an exception at this
 * line, and `try`/`catch` works across the boundary as it does anywhere else.
 *
 * [body] may not capture anything from around it: it runs in another process, where
 * the things it would have captured do not exist. Pass them as arguments instead,
 * which is checked at compile time.
 */
public suspend fun <A1, A2, A3, A4, A5, R> server(
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    a5: A5,
    @RpcLift("server") body: RpcBody5<ServerScope, A1, A2, A3, A4, A5, R>,
): R = rpcCallIn(node(SERVER_NODE), a1, a2, a3, a4, a5, body)

/**
 * Runs [body] on the client called [name] and returns what it produced.
 *
 * The name is the node's name, which for a game client is also its username.
 * Whether that client is running is not this driver's business: starting a process is
 * a job for whatever launched the cluster.
 *
 * @see server for the capture and argument rules, which are identical.
 */
public suspend fun <A1, A2, A3, A4, A5, R> client(
    name: String,
    a1: A1,
    a2: A2,
    a3: A3,
    a4: A4,
    a5: A5,
    @RpcLift("client") body: RpcBody5<ClientScope, A1, A2, A3, A4, A5, R>,
): R = rpcCallIn(node(name), a1, a2, a3, a4, a5, body)
