package dev.vibeported.mc.e2e

/*
 * Generated by tools/call-overloads.py. Edit that, not this.
 *
 * Every one of these throws. The compiler plugin rewrites each call site into `invokeProcedure` with the
 * ids and types it worked out, so a body that reaches this has been compiled without the plugin --
 * and saying so plainly beats failing later with something that looks like a transport problem.
 */

/**
 * Runs [body] on the dedicated server and returns what it produced.
 *
 * Called from the server itself the body runs in place, with these very objects. Called from
 * anywhere else the arguments are encoded, the block runs over there, and the result comes back --
 * so a failure inside it surfaces as an exception at this line, and `try`/`catch` works across the
 * boundary like it does anywhere else.
 *
 * [body] may not capture anything from around it: it runs in another process, where the things it
 * would have captured do not exist. Pass them as arguments instead, which is checked at compile
 * time.
 */
public suspend fun <R> server(body: suspend ServerScope.() -> R): R = notApplied("server")

/**
 * Runs [body] on the client called [name] and returns what it produced.
 *
 * The name is the client's username, and the client it addresses is started before the run if the
 * name could be worked out at compile time, or on demand the first time it is used if it could not.
 *
 * @see server for the capture and argument rules, which are identical.
 */
public suspend fun <R> client(name: String, body: suspend ClientScope.() -> R): R = notApplied("client")

// -- server, by arity ------------------------------------------------------

public suspend fun <A1, R> server(
    a1: A1,
    body: suspend ServerScope.(A1) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, R> server(
    a1: A1, a2: A2,
    body: suspend ServerScope.(A1, A2) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, A3, R> server(
    a1: A1, a2: A2, a3: A3,
    body: suspend ServerScope.(A1, A2, A3) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, A3, A4, R> server(
    a1: A1, a2: A2, a3: A3, a4: A4,
    body: suspend ServerScope.(A1, A2, A3, A4) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, A3, A4, A5, R> server(
    a1: A1, a2: A2, a3: A3, a4: A4, a5: A5,
    body: suspend ServerScope.(A1, A2, A3, A4, A5) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, A3, A4, A5, A6, R> server(
    a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6,
    body: suspend ServerScope.(A1, A2, A3, A4, A5, A6) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, A3, A4, A5, A6, A7, R> server(
    a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6, a7: A7,
    body: suspend ServerScope.(A1, A2, A3, A4, A5, A6, A7) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, A3, A4, A5, A6, A7, A8, R> server(
    a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6, a7: A7, a8: A8,
    body: suspend ServerScope.(A1, A2, A3, A4, A5, A6, A7, A8) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, A3, A4, A5, A6, A7, A8, A9, R> server(
    a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6, a7: A7, a8: A8, a9: A9,
    body: suspend ServerScope.(A1, A2, A3, A4, A5, A6, A7, A8, A9) -> R,
): R = notApplied("server")

public suspend fun <A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R> server(
    a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6, a7: A7, a8: A8, a9: A9, a10: A10,
    body: suspend ServerScope.(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) -> R,
): R = notApplied("server")


// -- client, by arity ------------------------------------------------------

public suspend fun <A1, R> client(
    name: String, a1: A1,
    body: suspend ClientScope.(A1) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, R> client(
    name: String, a1: A1, a2: A2,
    body: suspend ClientScope.(A1, A2) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, A3, R> client(
    name: String, a1: A1, a2: A2, a3: A3,
    body: suspend ClientScope.(A1, A2, A3) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, A3, A4, R> client(
    name: String, a1: A1, a2: A2, a3: A3, a4: A4,
    body: suspend ClientScope.(A1, A2, A3, A4) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, A3, A4, A5, R> client(
    name: String, a1: A1, a2: A2, a3: A3, a4: A4, a5: A5,
    body: suspend ClientScope.(A1, A2, A3, A4, A5) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, A3, A4, A5, A6, R> client(
    name: String, a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6,
    body: suspend ClientScope.(A1, A2, A3, A4, A5, A6) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, A3, A4, A5, A6, A7, R> client(
    name: String, a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6, a7: A7,
    body: suspend ClientScope.(A1, A2, A3, A4, A5, A6, A7) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, A3, A4, A5, A6, A7, A8, R> client(
    name: String, a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6, a7: A7, a8: A8,
    body: suspend ClientScope.(A1, A2, A3, A4, A5, A6, A7, A8) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, A3, A4, A5, A6, A7, A8, A9, R> client(
    name: String, a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6, a7: A7, a8: A8, a9: A9,
    body: suspend ClientScope.(A1, A2, A3, A4, A5, A6, A7, A8, A9) -> R,
): R = notApplied("client")

public suspend fun <A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R> client(
    name: String, a1: A1, a2: A2, a3: A3, a4: A4, a5: A5, a6: A6, a7: A7, a8: A8, a9: A9, a10: A10,
    body: suspend ClientScope.(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) -> R,
): R = notApplied("client")


private fun notApplied(what: String): Nothing = throw PluginNotAppliedException("$what { }")
