package dev.vibeported.mc.e2e

import dev.vibeported.mc.e2e.rpc.ValueCodec
import kotlinx.serialization.json.JsonElement

/**
 * The generated per-file dispatch table.
 *
 * The compiler plugin emits one of these per source file and per role -- a server table and a client
 * table -- holding every lifted block body as a private suspend method. Lookup is by a stable string
 * id, which is what lets a node run a block whose source lived in another process entirely.
 *
 * The split by role is not tidiness. A dedicated server is dist-cleaned, so client classes are not
 * on its classpath at all; one table holding both would be a class it could not verify.
 *
 * [scope] is untyped because it differs by role, and naming both types here would put a client-only
 * type in a signature the server has to resolve.
 */
public interface ProcedureTable {
    /**
     * Runs one block with arguments that are already the objects they claim to be.
     *
     * Throws [NoSuchProcedureException] if this table does not own the id. There is deliberately no
     * listing of what it does own: the generated index already records every block against its
     * table, and a second copy of that fact could drift from the first.
     */
    public suspend fun invoke(id: String, scope: Any, args: List<Any?>): Any?

    /**
     * Turns arguments that arrived over the wire back into objects.
     *
     * Done here rather than by the node because only the generated code knows what each parameter
     * was declared as. The node has a list of encoded values and no idea what they mean.
     */
    public fun decodeArgs(id: String, args: List<JsonElement>, codec: ValueCodec): List<Any?>

    /** Encodes what the block returned, for the same reason. Null when it returns nothing. */
    public fun encodeResult(id: String, value: Any?, codec: ValueCodec): JsonElement?
}

/**
 * Marks declarations that only the compiler plugin is meant to call.
 *
 * Calling one by hand is not unsafe so much as pointless: the arguments are ids and types the plugin
 * computes from the source it is rewriting.
 */
@RequiresOptIn(
    message = "This declaration is generated by the minecraft-e2e compiler plugin.",
    level = RequiresOptIn.Level.ERROR,
)
@Retention(AnnotationRetention.BINARY)
public annotation class PluginGenerated
